/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Counter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Игорь
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public UserForm() throws SQLException {
         mdbc=new MyDBConnection();
         mdbc.init();
         Connection conn=mdbc.getMyConnection();
         stmt= conn.createStatement();
        initComponents();
    }
        public ResultSet getResultFromUser() {
        ResultSet rs=null;
        
        try{    
            rs=stmt.executeQuery("SELECT * from user");
            }                        
        catch(SQLException e){} 
            return rs;

    }
//public ResultSet UserForm(){
//    String url="jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&serverTimezone =UTC ";
//    String username="root";
//    String password="";
//    ResultSet rs=null;
//    try{
//         String query="select * from users";
//         Connection connection=DriverManager.getConnection(url,username,password);
//       PreparedStatement preparedStatment=connection.prepareStatement(query);
//       rs=preparedStatment.executeQuery();
//        
//    }
//    catch(SQLException e){}
//        return rs;
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 65, 101));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Пользователи");
        jLabel1.setToolTipText("");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Логин:");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Пароль:");

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Изменить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Id:");

        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));

        jButton4.setText("Назад");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ResultSet rs=getResultFromUser();
        jTable1.setModel(new UserConnection(rs));
        jTable1.getTableHeader().setReorderingAllowed(false);
        mdbc.close(rs);
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Роль:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Работник", "Администратор" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPasswordField1))))
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String url="jdbc:mysql://localhost:3306/mydb?zeroDateTimeBehavior=convertToNull&serverTimezone =UTC ";
    String username="root";
    String password="";
    String Check1 = "";
    String Check2 = "";
    String query1="Select login from user";
    jLabel7.setText("");
    boolean log = false;
    int i,ch=0,b=0,p=0,k=0;
    
    char[] splitPassword = jPasswordField1.getPassword();
    try{
        String query="insert INTO user (login,password,role) VALUES(?,?,?)";
        String login=jTextField1.getText();
        String pass=jPasswordField1.getText();     
        String role=(String) jComboBox1.getSelectedItem();
       Connection connection=DriverManager.getConnection(url,username,password);
       PreparedStatement preparedStatment=connection.prepareStatement(query1);
       ResultSet rs=preparedStatment.executeQuery();
       while (rs.next()){
       Check1=rs.getString("login");
       //Проверка на существующего пользователя 
       if (Check1.equals(login)){
           k=1;
          jLabel7.setText("Пользователь есть в системе");
       }
       //Заполненность всех полей
       if ((login.equals(Check2))||(pass.equals(Check2)||(role.equals(Check2)))){
           p=1;
       jLabel7.setText("Заполните все поля (id необязательно)");}
       }
       //Содержание в пароле букв и цифр
       for(i = 0; i < jPasswordField1.getText().length(); i++){
        if(Character.isDigit(splitPassword[i])){
             ch++;
                 }
        if(Character.isLetter(splitPassword[i])){
            b++;
        }    
        if (ch==0||b==0){
        jLabel7.setText("Пароль должен состоять из букв и цифр");
        }else{
            jLabel7.setText("");
        }
        
         }  
       if (ch==0||b==0){
        jLabel7.setText("Пароль должен состоять из букв и цифр");
        }else{
        }
       //Проверка логина на содержание 5 символов
       if(jTextField1.getText().length()<5){
            
           jLabel7.setText("Login меньше 5 символов");
        }else{
            log = true;
        }
       if ((k==0) & (p==0) & (log=true) & (ch>=1)& (b>=1)) {
       preparedStatment=connection.prepareStatement(query);
       preparedStatment.setString(1,login);
       preparedStatment.setString(2,pass);
       preparedStatment.setString(3,role);
       int done=preparedStatment.executeUpdate();
       getContentPane().removeAll();
       initComponents();
       jLabel7.setText("Пользователь добавлен");
       }
    }catch(SQLException e){
        jLabel7.setText("Ошибка подключения к серверу");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String url="jdbc:mysql://localhost:3306/mydb?zeroDateTimeBehavior=convertToNull&serverTimezone =UTC ";
    String username="root";
    String password="";
    jLabel7.setText("");
    boolean log = false;
    int i,ch=0,b=0,p=0,k=0;
    
    char[] splitPassword = jPasswordField1.getPassword();
    try{
        String query="update user set login=?,password=?,role=? where iduser=? ";
        String login=jTextField1.getText();
        String pass=jPasswordField1.getText();        
        String id= jTextField5.getText();
        String role=(String) jComboBox1.getSelectedItem();
        jLabel7.setText("");
        String Check1 = "";
        //Заполненность всех полей
        if (id.equals(Check1)||login.equals(Check1)||pass.equals(Check1)||role.equals(Check1)){ 
       jLabel7.setText("Заполните все поля");}
       else{
        //Содержание в пароле букв и цифр
       for(i = 0; i < jPasswordField1.getText().length(); i++){
        if(Character.isDigit(splitPassword[i])){
             ch++;
                 }
        if(Character.isLetter(splitPassword[i])){
            b++;
        }    
        if (ch==0||b==0){
        jLabel7.setText("Пароль должен состоять из букв и цифр");
        }else{
        }
        
         }  
       //Проверка логина на содержание 5 символов
       if(jTextField1.getText().length()<5){
            
           jLabel7.setText("Login меньше 5 символов");
        }else{
            log = true;
        }
        if ((log=true) & (ch>=1)& (b>=1)){
        Connection connection=DriverManager.getConnection(url,username,password);
       PreparedStatement preparedStatment=connection.prepareStatement(query);
       preparedStatment.setString(1,login);
       preparedStatment.setString(2,pass);
       preparedStatment.setString(3,role);
       preparedStatment.setString(4,id);
       int done=preparedStatment.executeUpdate();
       getContentPane().removeAll();
       initComponents();
       jLabel7.setText("Данные пользователя изменены");}}
    }catch(SQLException e){
        jLabel7.setText("Ошибка подключения к серверу");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     String url="jdbc:mysql://localhost:3306/mydb?zeroDateTimeBehavior=convertToNull&serverTimezone =UTC ";
    String username="root";
    String password="";
    jLabel7.setText("");
    try{
        String query="DELETE FROM user WHERE iduser=?";
        String id= jTextField5.getText();
        jLabel7.setText("");
        String Check1 = "";
        if (id.equals(Check1)){
            jLabel7.setText("Id не выбран");
        }else{
        Connection connection=DriverManager.getConnection(url,username,password);
       PreparedStatement preparedStatment=connection.prepareStatement(query);
       preparedStatment.setString(1,id);
       int done=preparedStatment.executeUpdate();
       getContentPane().removeAll();
       initComponents();
       jLabel7.setText("Пользователь удалён");}
    }catch(SQLException e){
        jLabel7.setText("Ошибка подключения к серверу");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
private final MyDBConnection mdbc;
private final java.sql.Statement stmt;
//запрет на перемещение столбцов таблицы

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
